server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    #表示是否将自己注册进eureka server默认为true
    register-with-eureka: true
    #是否从eureka server抓取自己，单点无所谓，集群必须为true
    fetch-registry: true
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #      globalcors:
#        corsConfigurations:
#          '[/**]': # 匹配所有请求
#            allowedOrigins: "*" #跨域处理 允许所有的域
#            allowedMethods: # 支持的方法
#              - GET
#              - POST
#              - PUT
#              - DELETE
      routes:
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
          filters:
#            - StripPrefix=1
#            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#        #用户微服务
#        - id: changgou_user_route
#          uri: lb://user
#          predicates:
#            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
#          filters:
#            - StripPrefix=1
#
#        - id: changgou_order_route
#          uri: lb://order
#          predicates:
#            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
#          filters:
#            - StripPrefix=1