server:
  port: 8010
eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    #表示是否将自己注册进eureka server默认为true
    register-with-eureka: false
feign:
  hystrix:
    enabled: true